### ISSUE TITLE
Pawncc gives errors, add ; to includes

### ISSUE THREAD

**Issue by OKStyle** [vitei/pawnscript#1]
console.inc : 

const
    {
    black = 0,  /\* colours as per the ANSI Escape sequences, ISO 6429 */
    red,
    green,
    yellow,
    blue,
    magenta,
    cyan,
    white,
    }; <----

float.inc :

const floatround_method: {
  floatround_round = 0,
  floatround_floor,
  floatround_ceil,
  floatround_tozero,
  floatround_unbiased
}; <----
const anglemode: {
  radian = 0,
  degrees,
  grades
}; <----

file.inc

const filemode:
    {
    io_read = 0,        /\* file must exist _/
    io_write,           /_ creates a new file _/
    io_readwrite,       /_ opens an existing file, or creates a new file _/
    io_append,          /_ appends to file (write-only) */
    }; <----

const seek_whence:
    {
    seek_start = 0,
    seek_current,
    seek_end,
    }; <----

**Comment by dpwright** [comment]
This repo is just a mirror of the official pawn repository, which is managed by its creator, CompuPhase.  Please direct any patches / bug reports to them directly: http://www.compuphase.com/pawn/pawn.htm.  Thank you.
